//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssUploadImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> Material { get; set; }
        public Nullable<int> SizeId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual Order Order { get; set; }
        public virtual Size Size { get; set; }
    }
}
